config/routes.rb
Rails.application.routes.draw do
  resources :red_days
  root 'red_days#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/red_day.rb
class RedDay < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/red_days_controller.rb
class RedDaysController < ApplicationController
  before_action :set_red_day, only: [:show, :edit, :update, :destroy]

  # GET /red_days
  # GET /red_days.json
  def index
    @red_days = RedDay.all
  end

  # GET /red_days/1
  # GET /red_days/1.json
  def show
  end

  # GET /red_days/new
  def new
    @red_day = RedDay.new
  end

  # GET /red_days/1/edit
  def edit
  end

  # POST /red_days
  # POST /red_days.json
  def create
    @red_day = RedDay.new(red_day_params)

    respond_to do |format|
      if @red_day.save
        format.html { redirect_to @red_day, notice: 'Red day was successfully created.' }
        format.json { render :show, status: :created, location: @red_day }
      else
        format.html { render :new }
        format.json { render json: @red_day.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /red_days/1
  # PATCH/PUT /red_days/1.json
  def update
    respond_to do |format|
      if @red_day.update(red_day_params)
        format.html { redirect_to @red_day, notice: 'Red day was successfully updated.' }
        format.json { render :show, status: :ok, location: @red_day }
      else
        format.html { render :edit }
        format.json { render json: @red_day.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /red_days/1
  # DELETE /red_days/1.json
  def destroy
    @red_day.destroy
    respond_to do |format|
      format.html { redirect_to red_days_url, notice: 'Red day was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_red_day
      @red_day = RedDay.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def red_day_params
      params.require(:red_day).permit(:good_day)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/red_days_helper.rb
module RedDaysHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CycleOfCat</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  </head>

  <body class="container custpm-bg">
    <%= yield %>
  </body>
</html>

app/views/red_days/_form.html.erb
<%= form_with(model: red_day, local: true) do |form| %>
  <% if red_day.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(red_day.errors.count, "error") %> prohibited this red_day from being saved:</h2>

      <ul>
      <% red_day.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :good_day %>
    <%= form.date_select :good_day, id: :red_day_good_day %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/red_days/edit.html.erb
<h1>Editing Red Day</h1>

<%= render 'form', red_day: @red_day %>

<%= link_to 'Show', @red_day %> |
<%= link_to 'Back', red_days_path %>

app/views/red_days/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Red Days</h1>

<table class="custom-table">
  <thead>
    <tr>
      <th>Good day</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @red_days.each do |red_day| %>
      <tr>
        <td><%= red_day.good_day %></td>
        <td><button type="button" class="btn btn-default"><%= link_to 'show', red_day %> <i class="fa fa-eye"></i> </button></td>
        <td><button type="button" class="btn btn-default"><%= link_to 'edit', edit_red_day_path(red_day) %> <i class="fa fa-edit"></i> </button></td>
        <td><button type="button" class="btn btn-default"><%= link_to 'destroy', red_day, method: :delete, data: { confirm: 'Are you sure?' }  %> <i class="fa fa-trash"></i> </button></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button type="button" class="btn btn-success"><%= link_to 'New Red Day', new_red_day_path %> <i class="fa fa-heart"></i> </button>

app/views/red_days/new.html.erb
<h1>New Red Day</h1>

<%= render 'form', red_day: @red_day %>

<%= link_to 'Back', red_days_path %>

app/views/red_days/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Good day:</strong>
  <%= @red_day.good_day %>
</p>

<%= link_to 'Edit', edit_red_day_path(@red_day) %> |
<%= link_to 'Back', red_days_path %>